In [2]:
# cell 0
# install a package from a notebook
!pip install pandas

# …and then import it for use
import pandas as pd

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\sowmy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (3.0.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sowmy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.4.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sowmy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\sowmy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sowmy\appdata\local\packages\pythonsoftwarefoundation.python.3.13_qbz5n2kfra8p0\localcache\local-packages\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: C:\Users\sowmy\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [3]:
#Define a dictionary 'x'

x = {'Name': ['Rose','John', 'Jane', 'Mary'], 'ID': [1, 2, 3, 4], 'Department': ['Architect Group', 'Software Group', 'Design Team', 'Infrastructure'], 
      'Salary':[100000, 80000, 50000, 60000]}

#casting the dictionary to a DataFrame
df = pd.DataFrame(x)

#display the result df
df

   Name  ID       Department  Salary
0  Rose   1  Architect Group  100000
1  John   2   Software Group   80000
2  Jane   3      Design Team   50000
3  Mary   4   Infrastructure   60000

In [4]:
#Retrieving the "ID" column and assigning it to a variable x
x = df[['ID']]
x

   ID
0   1
1   2
2   3
3   4

In [5]:
#check the type of x
type(x)

pandas.DataFrame

In [6]:
#Retrieving the Department, Salary and ID columns and assigning it to a variable z

z = df[['Department','Salary','ID']]
z

        Department  Salary  ID
0  Architect Group  100000   1
1   Software Group   80000   2
2      Design Team   50000   3
3   Infrastructure   60000   4

In [7]:
a = {'Student':['David', 'Samuel', 'Terry', 'Evan'],
     'Age':['27', '24', '22', '32'],
     'Country':['UK', 'Canada', 'China', 'USA'],
     'Course':['Python','Data Structures','Machine Learning','Web Development'],
     'Marks':['85','72','89','76']}
df1 = pd.DataFrame(a)
df1

  Student Age Country            Course Marks
0   David  27      UK            Python    85
1  Samuel  24  Canada   Data Structures    72
2   Terry  22   China  Machine Learning    89
3    Evan  32     USA   Web Development    76

In [8]:
b= df1[['Marks']]
b

  Marks
0    85
1    72
2    89
3    76

In [9]:
x = df1['Student']
x

0     David
1    Samuel
2     Terry
3      Evan
Name: Student, dtype: str

In [10]:
df.iloc[0,2]

'Architect Group'

In [11]:
df2=df
df2=df2.set_index("Name")

In [12]:
#To display the first 5 rows of new dataframe
df2.head()

      ID       Department  Salary
Name
Rose   1  Architect Group  100000
John   2   Software Group   80000
Jane   3      Design Team   50000
Mary   4   Infrastructure   60000